apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapi.fullname" . }}
  labels:
    {{- include "flaskapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: 30002
  selector:
    {{- include "flaskapi.selectorLabels" . | nindent 4 }}
