replicaCount: 1

configMap:
  name: postgres-config
  app: postgres
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin 

postgres:
  deploymentName: postgres-deployment
  name: postgres
  containerName: postgres-container
  repository: postgres:13.1-alpine
  pullPolicy: "IfNotPresent"
  port: 5432
  envFrom: postgres-config 
  volume: mypostgresdb 
  env:
    name: POSTGRES_PASSWORD
    secretKeyRef:
      name: postgres-secret
      key: POSTGRES_PASSWORD
  volumeMounts:
      mountPath: /var/lib/postgresql/data
      name: mypostgresdb
  volumes:
      name: mypostgresdb
      claimName: postgres-pv-claim              

secret:
  name: postgres-secret
  type: Opaque
  POSTGRES_PASSWORD: YWRtaW5HMjAK
               	
service:
  name: postgres-service
  port: 5432
  targetPort: 5432
  app: postgres
  type: ClusterIP

storage:
  pv:
    name: postgres-pv-volume
    type: local
    app: postgres
    storageClassName: microk8s-hostpath
    capacity: 5Gi
    accessModes: ReadWriteMany
    path: "/opt/postgres/data"
  pvc:
    name: postgres-pv-claim
    app: postgres
    storageClassName: microk8s-hostpath
    accessModes: ReadWriteMany
    capacity: 5Gi
