apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
spec:
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.targetPort }}
      nodePort: {{ .Values.frontendService.nodePort }}
  selector:
    app: {{ .Values.frontendService.app }}
  type: {{ .Values.frontendService.type }}
    
