apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.deploymentName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.containerName }}
          image: {{ .Values.postgres.repository }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}  
          ports:
            - containerPort: {{ .Values.postgres.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgres.envFrom }}
          env:
            - name: {{ .Values.postgres.env.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.env.secretKeyRef.name }}
                  key: {{ .Values.postgres.env.secretKeyRef.key }}
          volumeMounts:             
            - name: {{ .Values.postgres.volumeMounts.name }}
              mountPath: {{ .Values.postgres.volumeMounts.mountPath }} 
      volumes:
        - name: {{ .Values.postgres.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.volumes.claimName }}
